name: Deploy Unstable Manual

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - main
    types:
      - completed
jobs:
  deploy-unstable:
    runs-on: ubuntu-latest

    steps:
      - uses: haya14busa/action-workflow_run-status@v1
      - uses: actions/checkout@v2.3.5
      - uses: cachix/install-nix-action@v15
        with:
          install_url: https://releases.nixos.org/nix/nix-2.4/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: colmena
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # == Manual
      - name: Build manual
        run: nix build .#manual -L

      - name: Deploy manual
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: result
          target-folder: unstable

      # == Redirect Farm
      # /future_api_version -> /unstable
      - name: Check future API version
        run: echo "api_version=$(nix eval .#colmena.apiVersion)" >> $GITHUB_ENV

      - name: Build redirect farm
        run: nix build .#manual.redirectFarm -L

      - name: Deploy redirect farm
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: result-redirectFarm
          target-folder: '${{ env.api_version }}'
